cc_test(
  name = "compact_suffix_array_test",
  size = "small",
  srcs = ["compact_suffix_array_test.cc"],
  deps = [
    "@com_google_googletest//:gtest_main",
    "//src/compact_suffix_array:compact_suffix_array"
  ],
)